name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git
        pip install --upgrade buildozer cython

    - name: Clean previous build
      run: |
        rm -rf .buildozer
        rm -rf ~/.buildozer

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: attendiq-apk
        path: bin/*.apk
